### ISSUE TITLE
Cool game! But not great on mobile

### ISSUE THREAD

**Issue by anton-gustafsson** [migearu/incremental-game#1]
I tried it on my phone and the responsiveness was not that good. Had to zoom in to read text and so on.

Are you using a css library or is it just hand made css? Let me know if you need any help

**Comment by migearu** [comment]
I could attempt to make the website horizontally aligned on mobile, however I don't know the feasibility of this.
If that doesn't work, I could make a separate website for mobile, but again, even if I do, it wouldn't be soon, mainly because of updating the main game first, and the fact that this is a passion project, so I work on it sporadically.

It is handmade CSS, since I wanted to learn how to actually use CSS instead of using a pre-built library.

**Comment by anton-gustafsson** [comment]
Alright! thank you for the update. I created a PR that hopefully fixes this issues. Let me know if you merge this :)
